# !!!
# !!! This file is for development purpose only !!!
# !!!
substitutions:
  # main prefix for all entities
  name: "Water Heater"
  # name of your node
  node_name: "water-heater"
  # use "esp12e" for iot-uni-dongle, "esp8285" for coolrf-heatstick
  board: "esp12e"
  # time platform: "sntp" or "homeassistant"
  time_platform: "homeassistant"
  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  # password of your wifi
  wifi_password: !secret wifi_password
  # password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password
  # version of ewh
  ewh_version: "master"

packages:
  ewh: !include ewh-pkg-ewh.yaml
  clock: !include ewh-pkg-clock.yaml
  timer: !include ewh-pkg-timer.yaml
  web: !include ewh-pkg-web.yaml # must follow before core and after ewh
  cloud: !include ewh-pkg-cloud.yaml # must follow before core
  core: !include ewh-pkg-core.yaml

external_components:
  - source: components
  # - source: github://pr#2688
  #   components: ["web_server"]

time:
  platform: $time_platform
  timezone: UTC-3

ewh_cloud:
  mac: !secret cloud_mac
  uid: !secret cloud_uid
# web_server:
#   version: 2
