substitutions:
  name: Water Heater
  node_name: water-heater

esphome:
  name: $node_name
  platform: ESP8266
  board: esp12e
  on_boot:
    then:
      - lambda: id(wh).sync_clock();

external_components:
  - source: github://dentra/esphome-ewh
  # - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$name Fallback Hotspot"
    password: "12345678"

captive_portal:
ota:
api:
  services:
    - service: exec
      variables:
        data: string
      then:
        lambda: id(wh).exec(data);
    - service: timer
      variables:
        hours: int
        minutes: int
        temperature: int
      then:
        lambda: id(wh).timer(hours, minutes, temperature);
  reboot_timeout: 0s
web_server:

logger:
  # Make sure logging is not using the serial port
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

time:
  - platform: sntp
    timezone: UTC-3
    on_time:
      seconds: 0
      minutes: /30
      then:
        - lambda: id(wh).sync_clock();

climate:
  - platform: ewh
    id: wh
    name: "$name"
    bst:
      name: $name BST #Bacteria Stop Technology
    clock:
      name: $name Clock
    timer:
      name: $name Timer

sensor:
  - platform: wifi_signal
    name: "$name WiFi Signal"

button:
  - platform: restart
    name: "$name Restart"

  - platform: template
    name: "$name Cmd 01"
    on_press:
      - lambda: id(wh).exec(0x01);
    entity_category: diagnostic

  - platform: template
    name: "$name Cmd 06"
    on_press:
      - lambda: id(wh).exec(0x06,{0,0,0,0,0,0,0,0,0,0,0,0,0,0x1a,0x07,0x32});
    entity_category: diagnostic

  - platform: template
    name: "$name Cmd 07"
    on_press:
      - lambda: id(wh).exec(0x07);
    entity_category: diagnostic

  - platform: template
    name: "$name Cmd 08"
    on_press:
      - lambda: id(wh).exec(0x08, {0x10, 0x04});
    entity_category: diagnostic

  - platform: template
    name: "$name Test Cmd 08"
    on_press:
      - lambda: id(wh).exec(0x08);
    entity_category: diagnostic

  - platform: template
    name: "$name Sync Clock"
    on_press:
      - lambda: id(wh).sync_clock();
    entity_category: diagnostic
